# Server Class
MAX_ATTEMPS_RESEND = 7

# MessageType Class
"""
Types des messages
"""
ACQUITTEMENT = 0
CONNEXION = 1
QUITTER_APP = 2
SELECTION_FILM = 3
QUITTER_FILM = 4
LISTE_FILMS = 5
LISTE_UTILISATEURS = 6
ACCEPTATION_UTILISATEUR = 7
REFUS_CONNEXION = 8
CHAT = 9

"""
Sizes of messages
"""
SIZE_ENTETE = 4  # Bytes
SIZE_MOVIE_PACK = 9
SIZE_TYPE = 4
SIZE_NUMERO_SEQUENCE = 12
